export const csvFieldDefinitions = [
    { name: "card_code", required: true },
    { name: "salutation", required: true },
    { name: "title", required: false },
    { name: "first_name", required: true, validate: "nonEmpty" },
    { name: "last_name", required: true, validate: "nonEmpty" },
    { name: "position", required: true },
    { name: "department", required: true },
    { name: "profile_image_name", required: false },
    { name: "card_email_1", required: false, validate: "email" },
    { name: "card_email_2", required: false, validate: "email" },
    { name: "card_email_3", required: false, validate: "email" },
    { name: "card_email_4", required: false, validate: "email" },
    { name: "card_phone_1", required: false, validate: "phone" },
    { name: "card_phone_2", required: false, validate: "phone" },
    { name: "card_phone_3", required: false, validate: "phone" },
    { name: "card_phone_4", required: false, validate: "phone" },
    { name: "card_address_1", required: false },
    { name: "card_address_2", required: false },
    { name: "card_address_3", required: false },
    { name: "card_address_4", required: false },
    { name: "card_button_text_1", required: false },
    { name: "card_button_link_1", required: false, validate: "url" },
    { name: "card_button_text_2", required: false },
    { name: "card_button_link_2", required: false, validate: "url" },
    { name: "card_button_text_3", required: false },
    { name: "card_button_link_3", required: false, validate: "url" },
    { name: "card_button_text_4", required: false },
    { name: "card_button_link_4", required: false, validate: "url" },
    { name: "social_link_1", required: false, validate: "url" },
    { name: "social_link_2", required: false, validate: "url" },
    { name: "social_link_3", required: false, validate: "url" },
    { name: "social_link_4", required: false, validate: "url" },
    { name: "social_link_5", required: false, validate: "url" },
];
